version: '3'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./portfolio:/app
      - /app/node_modules
      - /app/.next